// test/initGlobal.test.ts
import { describe, it, expect } from 'vitest';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { runInitGlobal } from '../src/commands/initGlobal.js';

function tmpHome() { return fs.mkdtempSync(path.join(os.tmpdir(), 'sehg-')); }

describe('runInitGlobal (v2)', () => {
  it('writes the global index and modules', () => {
    const home = tmpHome();
    const res = runInitGlobal({ home, tools: ['claude'] });
    const idx = path.join(home, '.seh', 'AGENTS.md');
    expect(fs.existsSync(idx)).toBe(true);
    const idxContent = fs.readFileSync(idx, 'utf8');
    expect(idxContent).toContain('GENERATED by seh');
    expect(idxContent).toContain('## Contents');
    expect(idxContent).toContain('](global/security.md)');
    expect(idxContent).toContain('[Security]');
    expect(fs.existsSync(path.join(home, '.seh', 'global', 'security.md'))).toBe(true);
    const cfg = JSON.parse(fs.readFileSync(path.join(home, '.seh', 'config.json'), 'utf8'));
    expect(cfg.tools).toEqual(['claude']);
    expect(res.created).toContain('AGENTS.md');
  });
  it('skips existing files without force', () => {
    const home = tmpHome();
    runInitGlobal({ home });
    const res = runInitGlobal({ home });
    expect(res.skipped).toContain('AGENTS.md');
  });
});
