// test/initGlobal.test.ts
import { describe, it, expect } from 'vitest';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { runInitGlobal } from '../src/commands/initGlobal.js';

function tmpHome() { return fs.mkdtempSync(path.join(os.tmpdir(), 'sehg-')); }

describe('runInitGlobal (v2)', () => {
  it('writes a single unified global AGENTS.md with inline sections (not an index)', () => {
    const home = tmpHome();
    const res = runInitGlobal({ home, tools: ['claude'] });
    const idx = path.join(home, '.seh', 'AGENTS.md');
    expect(fs.existsSync(idx)).toBe(true);
    const c = fs.readFileSync(idx, 'utf8');
    expect(c).toContain('GENERATED by seh');
    expect(c).not.toContain('## Contents');            // unified file, not an index
    expect(c).toContain('# Craftsmanship');
    expect(c).toContain('state of grace');
    expect(c).toContain('# Security');
    // global is one file: no separate module directory
    expect(fs.existsSync(path.join(home, '.seh', 'global'))).toBe(false);
    const cfg = JSON.parse(fs.readFileSync(path.join(home, '.seh', 'config.json'), 'utf8'));
    expect(cfg.tools).toEqual(['claude']);
    expect(res.created).toContain('AGENTS.md');
  });
  it('places the Craftsmanship section first', () => {
    const home = tmpHome();
    runInitGlobal({ home });
    const c = fs.readFileSync(path.join(home, '.seh', 'AGENTS.md'), 'utf8');
    expect(c.indexOf('# Craftsmanship')).toBeLessThan(c.indexOf('# Security'));
  });
  it('skips existing files without force', () => {
    const home = tmpHome();
    runInitGlobal({ home });
    const res = runInitGlobal({ home });
    expect(res.skipped).toContain('AGENTS.md');
  });
});
