// test/initGlobal.test.ts
import { describe, it, expect } from 'vitest';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { runInitGlobal } from '../src/commands/initGlobal.js';
import { PackageResolver } from '../src/package-resolver.js';
import { packageGlobalAgentsMd, packageGlobalDir } from '../src/paths.js';

function tmpHome() { return fs.mkdtempSync(path.join(os.tmpdir(), 'sehg-')); }

describe('runInitGlobal (v2)', () => {
  it('writes a single unified global AGENTS.md with inline sections (not an index)', () => {
    const home = tmpHome();
    const res = runInitGlobal({ home, agents: ['claude'] });
    const idx = path.join(home, '.seh', 'AGENTS.md');
    expect(fs.existsSync(idx)).toBe(true);
    const c = fs.readFileSync(idx, 'utf8');
    expect(c).toContain('GENERATED by seh');
    expect(c).not.toContain('## Contents');            // unified file, not an index
    expect(c).toContain('# Craftsmanship');
    expect(c).toContain('state of grace');
    expect(c).toContain('# Security');
    // global is one file: no separate module directory
    expect(fs.existsSync(path.join(home, '.seh', 'global'))).toBe(false);
    const cfg = JSON.parse(fs.readFileSync(path.join(home, '.seh', 'config.json'), 'utf8'));
    expect(cfg.agents).toEqual(['claude']);
    expect(res.created).toContain('AGENTS.md');
  });
  it('places the Craftsmanship section first', () => {
    const home = tmpHome();
    runInitGlobal({ home });
    const c = fs.readFileSync(path.join(home, '.seh', 'AGENTS.md'), 'utf8');
    expect(c.indexOf('# Craftsmanship')).toBeLessThan(c.indexOf('# Security'));
  });
  it('skips existing files without force', () => {
    const home = tmpHome();
    runInitGlobal({ home });
    const res = runInitGlobal({ home });
    expect(res.skipped).toContain('AGENTS.md');
  });
});

describe('runInitGlobal with resolver', () => {
  it('uses package global/AGENTS.md when present in resolver', () => {
    const home = tmpHome();
    const pkg = fs.mkdtempSync(path.join(os.tmpdir(), 'sehpkg-'));
    fs.mkdirSync(packageGlobalDir(pkg), { recursive: true });
    fs.writeFileSync(packageGlobalAgentsMd(pkg), '# Package Rules\n');
    const resolver = new PackageResolver(pkg);
    runInitGlobal({ home, resolver });
    const content = fs.readFileSync(path.join(home, '.seh', 'AGENTS.md'), 'utf8');
    expect(content).toBe('# Package Rules\n');
  });

  it('falls back to bundled when resolver has no global/AGENTS.md', () => {
    const home = tmpHome();
    const resolver = new PackageResolver(fs.mkdtempSync(path.join(os.tmpdir(), 'sehpkg-')));
    runInitGlobal({ home, resolver });
    const content = fs.readFileSync(path.join(home, '.seh', 'AGENTS.md'), 'utf8');
    expect(content).toContain('# Craftsmanship');
  });
});

describe('runInitGlobal with skills section', () => {
  it('appends a ## Skills section built from invoke metadata, after the ruleset', () => {
    const home = tmpHome();
    runInitGlobal({
      home,
      skills: {
        brainstorming: { type: 'vendor', invoke: { mode: 'when', condition: 'before build work' } },
        caveman: { type: 'vendor', invoke: { mode: 'always', label: 'compressed output' } },
        'find-skills': { type: 'vendor', invoke: { mode: 'optional' } },
      },
    });
    const c = fs.readFileSync(path.join(home, '.seh', 'AGENTS.md'), 'utf8');
    expect(c).toContain('## Skills');
    expect(c).toContain('Always invoke:');
    expect(c).toContain('- `caveman` — compressed output');
    expect(c).toContain('Invoke when:');
    expect(c).toContain('- `brainstorming` — before build work');
    expect(c).toContain('Optional:');
    expect(c).toContain('- `find-skills`');
    expect(c.indexOf('# Craftsmanship')).toBeLessThan(c.indexOf('## Skills'));
  });

  it('omits the Skills section when no skills carry invoke metadata', () => {
    const home = tmpHome();
    runInitGlobal({ home, skills: { x: { type: 'vendor' } } });
    const c = fs.readFileSync(path.join(home, '.seh', 'AGENTS.md'), 'utf8');
    expect(c).not.toContain('## Skills');
  });

  it('preserves packagePath in config.json when re-run with force', () => {
    const home = tmpHome();
    runInitGlobal({ home, agents: ['claude'] });
    const cfgFile = path.join(home, '.seh', 'config.json');
    const c = JSON.parse(fs.readFileSync(cfgFile, 'utf8'));
    c.packagePath = '/some/pkg';
    fs.writeFileSync(cfgFile, JSON.stringify(c));
    // as `seh package install --harness --force` does:
    runInitGlobal({ home, agents: ['claude', 'codex'], force: true });
    const after = JSON.parse(fs.readFileSync(cfgFile, 'utf8'));
    expect(after.packagePath).toBe('/some/pkg');
    expect(after.agents).toEqual(['claude', 'codex']);
  });

  it('appends the Skills section to a package global/AGENTS.md as well', () => {
    const home = tmpHome();
    const pkg = fs.mkdtempSync(path.join(os.tmpdir(), 'sehpkg-'));
    fs.mkdirSync(packageGlobalDir(pkg), { recursive: true });
    fs.writeFileSync(packageGlobalAgentsMd(pkg), '# Package Rules\n');
    const resolver = new PackageResolver(pkg);
    runInitGlobal({
      home,
      resolver,
      skills: { tdd: { type: 'vendor', invoke: { mode: 'when', condition: 'test-first' } } },
    });
    const c = fs.readFileSync(path.join(home, '.seh', 'AGENTS.md'), 'utf8');
    expect(c).toContain('# Package Rules');
    expect(c).toContain('## Skills');
    expect(c).toContain('- `tdd` — test-first');
  });
});
