import { describe, it, expect } from 'vitest';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { runPackageInit } from '../src/commands/package.js';
import {
  packageHarnessJson,
  packageGlobalAgentsMd,
  packageGlobalConfigJson,
  packageTemplatesStackDir,
  packageTemplatesProjectDir,
  packageProjectsDir,
} from '../src/paths.js';

function tmpDir(): string {
  return fs.mkdtempSync(path.join(os.tmpdir(), 'sehpkgcmd-'));
}

describe('runPackageInit', () => {
  it('creates full package structure', () => {
    const base = tmpDir();
    const p = path.join(base, 'my-harness');
    runPackageInit({ packagePath: p });

    expect(fs.existsSync(packageHarnessJson(p))).toBe(true);
    expect(fs.existsSync(path.join(p, 'CHANGELOG.md'))).toBe(true);
    expect(fs.existsSync(packageGlobalAgentsMd(p))).toBe(true);
    expect(fs.existsSync(packageGlobalConfigJson(p))).toBe(true);
    expect(fs.existsSync(packageTemplatesStackDir(p))).toBe(true);
    expect(fs.existsSync(packageTemplatesProjectDir(p))).toBe(true);
    expect(fs.existsSync(packageProjectsDir(p))).toBe(true);
  });

  it('harness.json has correct name from directory basename', () => {
    const base = tmpDir();
    const p = path.join(base, 'team-harness');
    runPackageInit({ packagePath: p });
    const pkg = JSON.parse(fs.readFileSync(packageHarnessJson(p), 'utf8'));
    expect(pkg.name).toBe('team-harness');
    expect(pkg.version).toBe('1.0.0');
  });

  it('copies all bundled stack modules into templates/stack/', () => {
    const base = tmpDir();
    const p = path.join(base, 'my-harness');
    runPackageInit({ packagePath: p });
    for (const tech of ['typescript', 'python', 'go', 'rust', 'java', 'javascript', 'c']) {
      expect(fs.existsSync(path.join(packageTemplatesStackDir(p), `${tech}.md`))).toBe(true);
    }
  });

  it('global/AGENTS.md is generated from bundled defaults when no existing global', () => {
    const base = tmpDir();
    const home = tmpDir(); // empty home — no ~/.seh/AGENTS.md
    const p = path.join(base, 'my-harness');
    runPackageInit({ packagePath: p, home });
    const content = fs.readFileSync(packageGlobalAgentsMd(p), 'utf8');
    expect(content).toContain('GENERATED by seh');
    expect(content).toContain('# Craftsmanship');
  });

  it('global/AGENTS.md copies existing ~/.seh/AGENTS.md when present', () => {
    const base = tmpDir();
    const home = tmpDir();
    fs.mkdirSync(path.join(home, '.seh'), { recursive: true });
    fs.writeFileSync(path.join(home, '.seh', 'AGENTS.md'), '# My Custom Rules\n');
    const p = path.join(base, 'my-harness');
    runPackageInit({ packagePath: p, home });
    expect(fs.readFileSync(packageGlobalAgentsMd(p), 'utf8')).toBe('# My Custom Rules\n');
  });

  it('throws when package already exists without --force', () => {
    const base = tmpDir();
    const p = path.join(base, 'my-harness');
    runPackageInit({ packagePath: p });
    expect(() => runPackageInit({ packagePath: p })).toThrow('already exists');
  });

  it('overwrites with --force', () => {
    const base = tmpDir();
    const p = path.join(base, 'my-harness');
    runPackageInit({ packagePath: p });
    expect(() => runPackageInit({ packagePath: p, force: true })).not.toThrow();
  });

  it('returns list of created files', () => {
    const base = tmpDir();
    const p = path.join(base, 'my-harness');
    const { created } = runPackageInit({ packagePath: p });
    expect(created).toContain('harness.json');
    expect(created).toContain('CHANGELOG.md');
    expect(created).toContain('global/AGENTS.md');
    expect(created).toContain('global/config.json');
    expect(created).toContain('templates/stack/typescript.md');
  });
});
