import { describe, it, expect } from 'vitest';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { runPackageInit, runPackageUse, runPackageStatus } from '../src/commands/package.js';
import {
  packageHarnessJson,
  packageGlobalAgentsMd,
  packageGlobalConfigJson,
  packageTemplatesStackDir,
  packageTemplatesProjectDir,
  packageProjectsDir,
  globalConfigFile,
} from '../src/paths.js';

function tmpDir(): string {
  return fs.mkdtempSync(path.join(os.tmpdir(), 'sehpkgcmd-'));
}

describe('runPackageInit', () => {
  it('creates full package structure', () => {
    const base = tmpDir();
    const p = path.join(base, 'my-harness');
    runPackageInit({ packagePath: p });

    expect(fs.existsSync(packageHarnessJson(p))).toBe(true);
    expect(fs.existsSync(path.join(p, 'CHANGELOG.md'))).toBe(true);
    expect(fs.existsSync(packageGlobalAgentsMd(p))).toBe(true);
    expect(fs.existsSync(packageGlobalConfigJson(p))).toBe(true);
    expect(fs.existsSync(packageTemplatesStackDir(p))).toBe(true);
    expect(fs.existsSync(packageTemplatesProjectDir(p))).toBe(true);
    expect(fs.existsSync(packageProjectsDir(p))).toBe(true);
  });

  it('harness.json has correct name from directory basename', () => {
    const base = tmpDir();
    const p = path.join(base, 'team-harness');
    runPackageInit({ packagePath: p });
    const pkg = JSON.parse(fs.readFileSync(packageHarnessJson(p), 'utf8'));
    expect(pkg.name).toBe('team-harness');
    expect(pkg.version).toBe('1.0.0');
  });

  it('copies all bundled stack modules into templates/stack/', () => {
    const base = tmpDir();
    const p = path.join(base, 'my-harness');
    runPackageInit({ packagePath: p });
    for (const tech of ['typescript', 'python', 'go', 'rust', 'java', 'javascript', 'c']) {
      expect(fs.existsSync(path.join(packageTemplatesStackDir(p), `${tech}.md`))).toBe(true);
    }
  });

  it('global/AGENTS.md is generated from bundled defaults when no existing global', () => {
    const base = tmpDir();
    const home = tmpDir(); // empty home — no ~/.seh/AGENTS.md
    const p = path.join(base, 'my-harness');
    runPackageInit({ packagePath: p, home });
    const content = fs.readFileSync(packageGlobalAgentsMd(p), 'utf8');
    expect(content).toContain('GENERATED by seh');
    expect(content).toContain('# Craftsmanship');
  });

  it('global/AGENTS.md copies existing ~/.seh/AGENTS.md when present', () => {
    const base = tmpDir();
    const home = tmpDir();
    fs.mkdirSync(path.join(home, '.seh'), { recursive: true });
    fs.writeFileSync(path.join(home, '.seh', 'AGENTS.md'), '# My Custom Rules\n');
    const p = path.join(base, 'my-harness');
    runPackageInit({ packagePath: p, home });
    expect(fs.readFileSync(packageGlobalAgentsMd(p), 'utf8')).toBe('# My Custom Rules\n');
  });

  it('throws when package already exists without --force', () => {
    const base = tmpDir();
    const p = path.join(base, 'my-harness');
    runPackageInit({ packagePath: p });
    expect(() => runPackageInit({ packagePath: p })).toThrow('already exists');
  });

  it('overwrites with --force', () => {
    const base = tmpDir();
    const p = path.join(base, 'my-harness');
    runPackageInit({ packagePath: p });
    expect(() => runPackageInit({ packagePath: p, force: true })).not.toThrow();
  });

  it('returns list of created files', () => {
    const base = tmpDir();
    const p = path.join(base, 'my-harness');
    const { created } = runPackageInit({ packagePath: p });
    expect(created).toContain('harness.json');
    expect(created).toContain('CHANGELOG.md');
    expect(created).toContain('global/AGENTS.md');
    expect(created).toContain('global/config.json');
    expect(created).toContain('templates/stack/typescript.md');
  });
});

describe('runPackageUse', () => {
  it('writes packagePath to ~/.seh/config.json', () => {
    const base = tmpDir();
    const home = tmpDir();
    const p = path.join(base, 'my-harness');
    runPackageInit({ packagePath: p, home });
    runPackageUse({ packagePath: p, home });
    const cfg = JSON.parse(fs.readFileSync(globalConfigFile(home), 'utf8'));
    expect(cfg.packagePath).toBe(path.resolve(p));
  });

  it('preserves existing tools in config.json', () => {
    const base = tmpDir();
    const home = tmpDir();
    fs.mkdirSync(path.join(home, '.seh'), { recursive: true });
    fs.writeFileSync(globalConfigFile(home), JSON.stringify({ agents: ['claude', 'codex'] }));
    const p = path.join(base, 'my-harness');
    runPackageInit({ packagePath: p, home });
    runPackageUse({ packagePath: p, home });
    const cfg = JSON.parse(fs.readFileSync(globalConfigFile(home), 'utf8'));
    expect(cfg.agents).toEqual(['claude', 'codex']);
    expect(cfg.packagePath).toBe(path.resolve(p));
  });

  it('throws when path does not exist', () => {
    const home = tmpDir();
    expect(() => runPackageUse({ packagePath: '/nonexistent/path', home }))
      .toThrow('does not exist');
  });

  it('throws when path has no harness.json', () => {
    const home = tmpDir();
    const p = tmpDir();
    expect(() => runPackageUse({ packagePath: p, home }))
      .toThrow('not a harness package');
  });
});

describe('runPackageStatus', () => {
  it('returns null packagePath when no config', () => {
    const home = tmpDir();
    const status = runPackageStatus({ home });
    expect(status.packagePath).toBeNull();
    expect(status.pkg).toBeNull();
  });

  it('returns null when config has no packagePath', () => {
    const home = tmpDir();
    fs.mkdirSync(path.join(home, '.seh'), { recursive: true });
    fs.writeFileSync(globalConfigFile(home), JSON.stringify({ agents: [] }));
    expect(runPackageStatus({ home }).packagePath).toBeNull();
  });

  it('returns package metadata and dir existence when active', () => {
    const base = tmpDir();
    const home = tmpDir();
    const p = path.join(base, 'my-harness');
    runPackageInit({ packagePath: p, home });
    runPackageUse({ packagePath: p, home });
    const status = runPackageStatus({ home });
    expect(status.packagePath).toBe(path.resolve(p));
    expect(status.pkg?.name).toBe('my-harness');
    expect(status.pkg?.version).toBe('1.0.0');
    expect(status.dirs['global/']).toBe(true);
    expect(status.dirs['templates/stack/']).toBe(true);
    expect(status.dirs['templates/project/']).toBe(true);
    expect(status.dirs['projects/']).toBe(true);
  });
});
