// test/sync.test.ts
import { describe, it, expect, beforeEach } from 'vitest';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { runSync } from '../src/commands/sync.js';

function tmp() { return fs.mkdtempSync(path.join(os.tmpdir(), 'seh-')); }

describe('runSync', () => {
  let root: string;
  beforeEach(() => {
    root = tmp();
    fs.mkdirSync(path.join(root, '.harness'), { recursive: true });
    fs.writeFileSync(path.join(root, '.harness', 'project.md'), '# Project\nMISSION');
  });

  it('writes CLAUDE.md and AGENTS.md with banner and content', () => {
    const res = runSync({ root, adapters: ['claude', 'agents'] });
    expect(res.written.sort()).toEqual(['AGENTS.md', 'CLAUDE.md', 'harness.lock']);
    const claude = fs.readFileSync(path.join(root, 'CLAUDE.md'), 'utf8');
    expect(claude).toContain('GENERATED by seh');
    expect(claude).toContain('MISSION');
    expect(claude).toContain('Prime directives');
  });

  it('writes a valid lock file', () => {
    runSync({ root, adapters: ['claude'] });
    const lock = JSON.parse(fs.readFileSync(path.join(root, 'harness.lock'), 'utf8'));
    expect(lock.version).toBe('0.1.0');
    expect(lock.adapters).toEqual(['claude']);
  });

  it('is idempotent for generated content', () => {
    runSync({ root, adapters: ['claude'] });
    const first = fs.readFileSync(path.join(root, 'CLAUDE.md'), 'utf8');
    runSync({ root, adapters: ['claude'] });
    const second = fs.readFileSync(path.join(root, 'CLAUDE.md'), 'utf8');
    expect(second).toBe(first);
  });
});
