// test/sync.test.ts
import { describe, it, expect, beforeEach } from 'vitest';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { runSync } from '../src/commands/sync.js';

function tmp() { return fs.mkdtempSync(path.join(os.tmpdir(), 'sehsync-')); }

describe('runSync (v2)', () => {
  let root: string;
  beforeEach(() => {
    root = tmp();
    fs.mkdirSync(path.join(root, '.seh', 'domain'), { recursive: true });
    fs.writeFileSync(path.join(root, '.seh', 'project.md'), '# Project\nMISSION');
    fs.writeFileSync(path.join(root, '.seh', 'domain', 'glossary.md'), '# Glossary\nX');
  });

  it('writes stack modules and a linked index', () => {
    const res = runSync({ root, technologies: ['typescript', 'go'] });
    expect(fs.existsSync(path.join(root, '.seh', 'stack', 'typescript.md'))).toBe(true);
    expect(fs.existsSync(path.join(root, '.seh', 'stack', 'go.md'))).toBe(true);
    const idx = fs.readFileSync(path.join(root, 'AGENTS.md'), 'utf8');
    expect(idx).toContain('GENERATED by seh');
    expect(idx).toContain('](.seh/project.md)');
    expect(idx).toContain('](.seh/domain/glossary.md)');
    expect(idx).toContain('](.seh/stack/typescript.md)');
    expect(res.written).toContain('AGENTS.md');
    expect(res.written).toContain('seh.lock');
  });

  it('writes a lock with technologies', () => {
    runSync({ root, technologies: ['python'] });
    const lock = JSON.parse(fs.readFileSync(path.join(root, 'seh.lock'), 'utf8'));
    expect(lock.version).toBe('0.2.0');
    expect(lock.technologies).toEqual(['python']);
  });

  it('produces an idempotent index', () => {
    runSync({ root, technologies: ['typescript'] });
    const a = fs.readFileSync(path.join(root, 'AGENTS.md'), 'utf8');
    runSync({ root, technologies: ['typescript'] });
    const b = fs.readFileSync(path.join(root, 'AGENTS.md'), 'utf8');
    expect(b).toBe(a);
  });
});
