export const BANNER =
  '<!-- GENERATED by seh — do not edit. Edit .harness/ sources and run `seh sync`. -->';

export type Layer = {
  name: 'L0' | 'L1' | 'L2';
  source: string;
  content: string;
};

const ORDER: Record<Layer['name'], number> = { L0: 0, L1: 1, L2: 2 };

export function compose(layers: Layer[]): string {
  const sorted = [...layers].sort((a, b) => ORDER[a.name] - ORDER[b.name]);
  const blocks = sorted.map(
    (l) => `<!-- source: ${l.name} (${l.source}) -->\n${l.content.trim()}`
  );
  return [BANNER, ...blocks].join('\n\n') + '\n';
}
